# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Dependency install & start development server
    init: yarn install
    command: yarn dev

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    name: API route
    description: For data fetching
    onOpen: open-browser
    visibility: public
